fagotist96/fro 25 верстка форума
Glazoff/client-server-template-with-vite pull request #10
Opened 2024-01-24 21:29 UTC by IliaBYK

Какую задачу решаем
Задача - https://linear.app/frontwear/issue/FRO-25/verstka-foruma

Сверстать страницы форума.

Скриншоты/видяшка (если есть)
TBD (если есть)
В рамках задачи были сверстаны страницы форума: главная страница форума, страница комментариев топика, страница создания топика.
Реализован функционал перехода между страница, в частности переход на страницу комментариев определенного топика (на данный момент захаркожены карточки топиков и сами топики).

2024-01-25 16:51 UTC, RinVeber commented on packages/client/src/App/Router/routerPaths.tsx
>          path: 'add-topic',
Предложение.
Можно вместо строки в path указать константу. У нас же есть отдельная константа для этого. 
Будет 1 точка входа для изменения наименование роутов.

2024-01-25 16:52 UTC, RinVeber commented on packages/client/src/features/ForumAddTopicMain/index.tsx
> +            navigate(`${path.Forum}`);
Вот здесь это отлично)

2024-01-25 16:59 UTC, IliaBYK commented on packages/client/src/App/Router/routerPaths.tsx
>          path: 'add-topic',
Сделал

2024-01-25 17:00 UTC, RinVeber commented on packages/client/src/widgets/ForumTopicPage/index.tsx
> +    setValue((e.target as HTMLInputElement).value);
Вопрос.
Ты указал ```(e: React.ChangeEvent<HTMLInputElement>```, но потом принудительно преобразовал ```(e.target as HTMLInputElement```. Зачем?
Если есть ошибка typesript, то скорей всего это из-за того, что value useState не типизирован. Нужно его протипизировать.

2024-01-25 18:06 UTC, Glazoff approved these changes
Хорошая работа!
Есть пару коментов, не критичные

2024-01-25 18:06 UTC, Glazoff commented on packages/client/src/utils/forumCards.ts
> +const cards = [
по сути это похоже на моковые данные, мб переименовать файл или завести под них отд папку mock ?

2024-01-25 18:06 UTC, Glazoff commented on packages/client/src/features/ForumFooterBtns/index.tsx
> +          navigate(`${path.Forum}`);
`navigate(`${path.Forum}`)` можно вынести в отд функцию и передать ее вот так `onClick={onClickButton}`

2024-01-25 18:06 UTC, Glazoff commented on packages/client/src/features/ForumTopicCard/index.tsx
> +    <Link to={props.path} className={styles.card__container}>
Пропсы можно деструктуризировать - опционально.

2024-01-25 18:06 UTC, Glazoff commented on packages/client/src/widgets/ForumTopicPage/index.tsx
> +          onClick={() => {
лучше вынести это в отд функцию

2024-01-25 18:06 UTC, Glazoff commented on packages/client/src/widgets/ForumTopicPage/index.tsx
> +        label={cards.find((card) => card.id.toString() === id)?.text || ''}
лучше эту логику тоже вынести в отд функцию

2024-01-27 14:05 UTC, Olegas requested changes
Добрый день. Есть ряд замечаний по коду. Написал комментарии с пояснениями где и что надо поправить. Давай доработаем и будет все круто!

2024-01-27 14:05 UTC, Olegas commented on packages/client/src/features/CommentCard/index.tsx
> +  src: string;
По названию не понятно, что это за свойство. Source? Источник? Источник чего? Если это аватар то лучше назвать avatarUrl

2024-01-27 14:05 UTC, Olegas commented on packages/client/src/features/ForumTopicCard/index.tsx
> +        <p className={styles.card__counter}>Кол-во сообщений - {props.counter}</p>
Тип поля counter задекларирован как опциональный. Получается его можно не передавать? Но тогда в этой строке будет что-то типа "Кол-во сообщений - undefined". Надо или проверку добавлять или делать что бы поле было обязательным. Мне кажется второе правильнее, ведь если решили выводить количество сообщений, значит это обязательная информация

2024-01-27 14:05 UTC, Olegas commented on packages/client/src/shared/button/index.tsx
> +      onClick={props.onClick}
Не будет ли тут ошибки, если обработчик нажатия не будет передан? Ведь в типе свойство объявлено опциональным (Кстати зачем? Какой толк от кнопки, которая ничего не делает?)

2024-01-27 14:05 UTC, Olegas commented on packages/client/src/widgets/ForumTopicPage/index.tsx
> +  const label = cards.find((card) => card.id.toString() === id)?.text || '';
Операция поиска нужной "карточки" уже есть выше, на 12 строке. Не надо дублировать вычисления.

2024-01-27 14:05 UTC, Olegas commented on packages/client/src/widgets/ForumTopicPage/index.tsx
> +              key={comments.indexOf(comment)}
1. Если нужен индекс элемента, он есть вторым аргументом в функции map, не надо его вычислять путем поиска здесь
2. Ключи на основе индекса массива не очень хорошая затея. Он как бы есть но толку от него не много. Лучше тут выбрать какой-то другой ключ. Например время отправки + никнейм

2024-01-27 14:50 UTC, Olegas approved these changes
Работа принята

2024-01-27 14:51 UTC, merged