компонент авторизации и регистрации
Glazoff/client-server-template-with-vite pull request #11
Opened 2024-01-25 08:08 UTC by kalikrit

react-компонент (страница) авторизации и регистрации

![image](https://github.com/Glazoff/client-server-template-with-vite/assets/7803486/95600c7c-f8dc-4880-bce6-14654efa2e22)

![image](https://github.com/Glazoff/client-server-template-with-vite/assets/7803486/5c2b2090-d80d-4714-85f3-a1821d0f4d91)

2024-01-25 17:41 UTC, Glazoff approved these changes
Хорошая работа для начинающего в React!
Коммент с атрибутом name надо исправить

2024-01-25 17:41 UTC, Glazoff commented on packages/client/src/pages/Login/index.tsx
> +            Вход
Тут на свое усмотрение. 
Текста можно вынести в отдельные константы или в один объект с ключами и завести под них отдельный файл с константами.  В компонентах повторяются текст и в будущем будет проще текст менять.

2024-01-25 17:41 UTC, Glazoff commented on packages/client/src/pages/Login/index.tsx
> +            fullWidth={true}
Для каждого `TextField` нужно указать атрибут `name` согласно описанию задачи. 
По своей сути `TextField` это тот же компонент нативный `<Input />`, поэтому у него так же есть все базоые атрибуты `name`, `disabled` и тд

2024-01-26 11:33 UTC, kalikrit commented on packages/client/src/pages/Login/index.tsx
> +            fullWidth={true}
сделал

2024-01-26 12:08 UTC, kalikrit commented on packages/client/src/pages/Login/index.tsx
> +            Вход
сделал словарь вида:
```
const BUTTONS = {
  enter: {
    ru: {
      text: 'Вход',
    },
  },
  register: {
    ru: {
      text: 'Регистрация',
    },
  },
};
```
использую в обоих компонентах

2024-01-26 12:56 UTC, RinVeber commented on packages/client/src/pages/Login/index.tsx
> +            <Button sx={{ marginTop: 2, marginBottom: 2, width: '50%' }} variant="contained">
variant="contained" - это тот который предлагает mui по дефолту с синим цветом.
У нас в проекте добавлен variant = 'default' - тоже с синим цветом. 
У них radiusBorder разный. 
На скриншоте прикрепленный к ПР посмотри)

2024-01-26 12:59 UTC, RinVeber commented on packages/client/src/pages/Registration/index.tsx
> +    <div className="root">
Вопрос/предложение.
Проект обернут в muiTheme. 
Там тоже задаются корневые стили для страниц. 
Они могут перебивать друг друга и позже баги разметка этой страницы и других станут заметны из-за этого. 
Как быть?

2024-01-26 13:03 UTC, kalikrit commented on packages/client/src/pages/Login/index.tsx
> +            <Button sx={{ marginTop: 2, marginBottom: 2, width: '50%' }} variant="contained">
да, я заметил
сделаю default

2024-01-27 14:11 UTC, Olegas requested changes
Добрый день. Вопросы к описанию стилей. Точно ли их нужно писать инлайном а не через CSS? Если таки нужно, то стили надо вынести за рамки компонента, т.к. они всегда одинаковые а их инлайновое описание приводит к перерендерам т.к. значение свойства будет каждый раз новое.

2024-01-27 14:11 UTC, Olegas commented on packages/client/src/pages/Login/index.tsx
> +      <form className="form" style={{ marginTop: 100 }}>
Объект со стилем никогда не меняется. Его можно вынести за границы компонента что бы он всегда был буквально один и тот же и не триггерил рендеринг дерева ниже

2024-01-27 14:11 UTC, Olegas commented on packages/client/src/pages/Login/index.tsx
> +    </div>
В этом файле много стилей которые а) повторяются б) постоянные и могут быть вынесены за границы компонента

2024-01-27 14:11 UTC, Olegas commented on packages/client/src/pages/Registration/index.tsx
> +            <Button sx={{ marginTop: 2, marginBottom: 2, width: '50%' }} variant="contained">
Вот эти отступы вертикальные - их не проще на контейнер вынести?

2024-01-28 12:44 UTC, kalikrit commented on packages/client/src/pages/Login/index.tsx
> +      <form className="form" style={{ marginTop: 100 }}>
убрал div.root,
убрал стили из form

2024-01-28 12:44 UTC, kalikrit commented on packages/client/src/pages/Registration/index.tsx
> +            <Button sx={{ marginTop: 2, marginBottom: 2, width: '50%' }} variant="contained">
убрал отступы из кнопок, перенес в Stack

2024-01-28 12:45 UTC, kalikrit commented on packages/client/src/pages/Login/index.tsx
> +    </div>
убрал div
добавил 2 Box

2024-01-29 17:22 UTC, Olegas requested changes
Я не понял что поменялось.
Был стиль например style={{ marginTop: 100 }} стал sx={{ display: 'flex', height: '100vh' }}
Проблема никуда не делась. Все также на каждый рендер создается объект, передается в свойства компоненты что вызывает его перерисовку.
Если не хочется использовать CSS то хотя бы надо мемоизировать объекты или выносить их за границы компонента.

2024-01-30 08:05 UTC, kalikrit commented
@Olegas, Олег,
похоже я с самого начала не до конца понял, что собственно не так...
1. Вы указали на дублированные вертикальные отступы в кнопках и что надо их перенести в  блок выше. Я перенес, отступы из кнопок убрал
2. Вы указали на ненужные дивы и стили. Я их тоже убрал.

теперь речь уже идет о перерендеринге и мемоизации...
объясните, пожалуйста, что конкретно, по Вашему мнению, следует сделать в таких простых компонентах и почему.

2024-01-30 09:15 UTC, Olegas commented
@kalikrit Я в самом первом ревью написал: "Вопросы к описанию стилей. Точно ли их нужно писать инлайном а не через CSS? Если таки нужно, то стили надо вынести за рамки компонента, т.к. они всегда одинаковые а их инлайновое описание приводит к перерендерам т.к. значение свойства будет каждый раз новое."

Я вижу следующие проблемы:
1. Дублирование. Стили дублируются в рамках даже одного компонента.
2. Создание лишних объектов. Каждый рендер твоего компонента приводит к созданию новых объектов. Такая практика дает следующие минусы: а) дочерние компоненты перерисовываются, т.к. у них поменялись пропсы б) это дает дополнительную нагрузку на Garbage Collector. 

Способ решения: либо использовать нормальный CSS (styled, css-modules, обычные стили) либо мемоизировать объекты со стилями (либо useMemo если они таки могут меняться или зависят от чего-то, либо просто вынести в константу за границами компонента).

Я согласен что для таких простых компонентов и достаточно простого приложения это не будет проблемой, но т.к. мы здесь учимся то я считаю должным указать на недостатки данного подхода.

В целом, если у вас в проекте принят такой подход к стилизации компонентов - ок, давай так оставим. Я готов принять работу.

2024-01-30 10:57 UTC, kalikrit commented
@Olegas, Олег,
мы пообщались с ментором и тимлидом
решили вынести вопрос со стилями для компонентов в отдельную задачу
и решить в рамках этой задаче позже

2024-01-30 11:01 UTC, Olegas commented
@kalikrit ок, верни тогда задачу на приему, я приму

2024-01-30 11:50 UTC, kalikrit commented
@Olegas, Олег,
задачу вернул - снова отправил ПР на ревью

2024-01-30 12:00 UTC, Olegas approved these changes
Работа принята

2024-01-30 12:03 UTC, merged