Rinveber/fro 35 реализовать одну из игровых механик описанных в документе с
Glazoff/client-server-template-with-vite pull request #15
Opened 2024-02-04 12:38 UTC by RinVeber

### Какую задачу решаем

Задача: https://linear.app/frontwear/issue/FRO-35/realizovat-odnu-iz-igrovyh-mehanik-opisannyh-v-dokumente-s-logikoj

-- создан основной класс движка и gameLoop игры
-- созданы методы которые реагирует на нажатия клавиш
-- создан класс Волка и его анимация
-- создан класс Яиц и их анимация

-- Реализовано пересечение объектов. Подсчет пойманных яиц.
### Скриншоты/видяшка (если есть)

https://github.com/Glazoff/client-server-template-with-vite/assets/96541093/c0633cc3-ce93-483c-9a84-1c8ead949070

### TBD (если есть)

2024-02-04 14:25 UTC, Glazoff approved these changes

2024-02-04 14:25 UTC, Glazoff commented on packages/client/src/entries/GameEngine/Intersection.ts
> +    // if (
Данный комментарий еще нужен?

2024-02-04 14:25 UTC, Glazoff commented on packages/client/src/widgets/MainGamePage/index.tsx
> +      canvas.width = 720;
720 и 400 можно вынести в константы, они повторяются

2024-02-05 16:34 UTC, Olegas requested changes
Добрый день.
Есть вопросы по коду. Написал комментарии с замечаниями. Прошу доработать.

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/widgets/MainGamePage/index.tsx
> +      <Imagine src="../src/images/wolf.png" class={styles.game__img} /> */}
Не надо оставлять в проекте закомментированный код. Если не нужно - смело удаляй. Если нужно - оставь комментарий зачем сейчас закомментировал.

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/pages/Registration/index.tsx
> +  return <h1>Страница регистрации</h1>;
Вот тут явно что-то не то. Была страница регистрации а теперь просто текст.

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/pages/Login/index.tsx
> +    <h1>
Еще один компонент замене на что-то непонятное.

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +  constructor({ x, y }: { x: number; y: number; width: number; height: number; speed: number }) {
1. Тип лучше вынести отдельно. Можно прямо в этом файле. Так будет лучше читаться
2. А зачем в типе так много опций, а используется только две?

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +    this.eggImage.src = this.frames[this.currentAnimationFrame];
Если так, то на 22 строке присвоение лишнее получается?

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +  update = (canvasHeight: number) => {
А для чего аргумент? Он не используется

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +  draw = (ctx: CanvasRenderingContext2D) => {
Очень странно обявляются методы. Вместо нормального метода класса делается свойство, в которое складывается стрелочная функция. Для чего так нужно делать? Почему нельзя воспользоваться обычном методом класса?

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Engine.ts
> +    window.addEventListener('keyup', this.handleKeyUp);
Подписку на события добавили, а отписки от событий - нет. У тебя есть метод stop который ты вызываешь при разрушении компонента игры. Самое место там сделать отписку.

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Engine.ts
> +    if (event.code === 'ArrowLeft' || event.code === 'ArrowRight') {
Полностью задублирована проверка. Можно внести то что тут внутри в первую проверку и избежать дублирования.

2024-02-05 16:34 UTC, Olegas commented on packages/client/src/entries/GameEngine/Engine.ts
> +      if (this.wolf) {
А для чего проверять на wolf? Он же в конструкторе создается.

2024-02-06 11:49 UTC, RinVeber commented on packages/client/src/widgets/MainGamePage/index.tsx
> +      <Imagine src="../src/images/wolf.png" class={styles.game__img} /> */}
Исправил. 

При разработке классов для игры, мне нужно было увидеть результат и проверить "работает или нет". 
Вставил в существующую страничку, закоментировав, что там уже было. А потом забыл, вернувшись к классам движка игры.

По хорошему надо было создать новую страничку и вставить канвас туда и дальше работать так(

2024-02-06 11:52 UTC, RinVeber commented on packages/client/src/pages/Registration/index.tsx
> +  return <h1>Страница регистрации</h1>;
У меня произошел конфликт при подтягивания из ветки дев. 

Когда закоммитил свой код, то были проблемы с веткой дев. Я подтянул "новый" код из дев и плохо смержил конфликты видимо. 
Теперь не могу подтянуть код внутри этих компонентов из dev. 

Сейчас снова подтянул новые изменения из dev, но эти компоненты как были так и остались. Странно.
Только вручную вставить код из гита сюда могу...

2024-02-06 11:58 UTC, RinVeber commented on packages/client/src/pages/Login/index.tsx
> +    <h1>
Произошло из-за невнимательного решения конфликтов с веткой dev с моей стороны(

2024-02-06 12:12 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Egg.ts
> +  constructor({ x, y }: { x: number; y: number; width: number; height: number; speed: number }) {
1. Тип вынес отдельно. Оставил в этом фаиле.
2. На этапе разработки не понятно было, что мне пригодиться, а что нет. В команде договорились, что будет несколько типов яиц. Я думал найти картинки, вставить их и отрегулировать высоту/ширину в случае чего. 

Изменение скорости тоже нужно, чтобы сделать некоторые типы яиц более быстрыми или наоборот медленными. В основном заделки на будущее. На данном этапе это явно не нужно пока(

2024-02-06 12:18 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Egg.ts
> +    this.eggImage.src = this.frames[this.currentAnimationFrame];
У яиц должна быть какая то смена картинки в зависимости от того поймал ли его волк или оно разбилось. 
Я хотел закинуть в массив (frames) несколько картинок, а потом в случае чего подставлять нужную мне картинку из массива в зависимости от ситуации. 

Есть идея, но нет должного понимания как это сделать. 
Такой метод увидел в одном из обучающих роликов по канвасу в интернете.

2024-02-06 12:18 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Egg.ts
> +  update = (canvasHeight: number) => {
Удалил. 

У меня долгое время не исправно работал этот метод и я много с ним возился, пока яийца не начали плавно падать.
Забыл стереть аргумент.

2024-02-06 12:37 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Egg.ts
> +  draw = (ctx: CanvasRenderingContext2D) => {
У меня были проблемы с методом объявление. 
Иногда метод не распознавал контекст this и я у не знал как исправить, кроме как сделать ее стрелочной. 
Так же была и другая проблема - в браузере все работало как задумано, но консоль в браузере постоянно спамил об ошибке, что не распознается пропс в методе. 

Переделывание на стрелочный тип помогало решить проблему. Затем начал все делать так.

2024-02-06 12:37 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Egg.ts
> +  draw = (ctx: CanvasRenderingContext2D) => {
Я исправил большинство методы на обычные

2024-02-06 12:39 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Engine.ts
> +    window.addEventListener('keyup', this.handleKeyUp);
Сделал

2024-02-06 12:45 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Engine.ts
> +    if (event.code === 'ArrowLeft' || event.code === 'ArrowRight') {
Исправил

2024-02-06 12:49 UTC, RinVeber commented on packages/client/src/entries/GameEngine/Engine.ts
> +      if (this.wolf) {
Исправил. 
Проверка тут лишняя явно

2024-02-06 13:28 UTC, RinVeber commented
Разрешил конфликты с дев веткой в компоненте Login

2024-02-06 13:40 UTC, RinVeber commented
Исправил замечание по ревью.
Решил конфликты с новыми изменениями в дев ветке.

2024-02-06 15:21 UTC, Olegas approved these changes
Работа принята

2024-02-06 15:23 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +  draw = (ctx: CanvasRenderingContext2D) => {
Тут секрет был в том, что когда у тебя просто метод, и ты передаешь его, например, в requestAnimationFrame как-то так `requestAnimationFrame(this.nextFrame)` то при вызове контекст потеряется. А если у тебя свойство и стрелочная функция то у нее контекст всегда будет один.

2024-02-06 15:24 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +    this.eggImage.src = this.frames[this.currentAnimationFrame];
Нормально присваивать src картинке, просто не понятно зачем присваивать сначала один а потом сразу другой. Мой комментарий был только об этом.

2024-02-06 15:25 UTC, Olegas commented on packages/client/src/entries/GameEngine/Egg.ts
> +  constructor({ x, y }: { x: number; y: number; width: number; height: number; speed: number }) {
Надо только speed использовать из аргументов, а то сейчас просто константа а аргумент не использован.

2024-02-06 15:56 UTC, merged