Fagotist96/fro 36 реализовать состояние начало и состояние завершение игры
Glazoff/client-server-template-with-vite pull request #17
Opened 2024-02-05 15:02 UTC by IliaBYK

### Задача в linear: https://linear.app/frontwear/issue/FRO-36/realizovat-sostoyanie-%C2%ABnachalo%C2%BB-i-sostoyanie-%C2%ABzavershenie-igry%C2%BB

-- создана базовая механика игры, так как основная находится на ревью
-- реализованы: окончание игры, отображение экрана завершения с количеством заработанных очков, возможность перезапуска игры

### Скриншоты/видяшка (если есть)

https://github.com/Glazoff/client-server-template-with-vite/assets/107132756/1af55a1c-64d6-44e5-a83a-cb0597f8a860

### TBD (если есть)

2024-02-05 19:19 UTC, Glazoff approved these changes

2024-02-05 19:19 UTC, Glazoff commented on packages/client/src/widgets/MainPage/index.tsx
> +          navigate(`${path.Game}`);
мы можем просто передать `path.Game` без обратных кавычек

2024-02-05 19:19 UTC, Glazoff commented on packages/client/src/widgets/GameOverPage/index.tsx
> +  const score = window.localStorage.getItem('score') || 0;
Я бы тут подумал что выводить вместо 0. Если по какой то причине движок не сохранил значения в локалСтор, то не совсем корректно выводить 0 баллов, а лучше бы вывести текст с ошибкой тип ("не удалось сохранить набранные очки ").
Но если на фикс займет много времени, то давай пока оставим так и в будущем пофиксим.

2024-02-05 19:19 UTC, Glazoff commented on packages/client/src/pages/GameOver/index.tsx
> +interface Props {
Я б назвал интерфейс более информативно, тип `PropsGameOver` - на свое усмотрение.

2024-02-05 20:00 UTC, Olegas commented
@IliaBYK добрый вечер. А почему в этом PR часть кода такая-же как вот в этом https://github.com/Glazoff/client-server-template-with-vite/pull/15/commits ? Такое впечатление что вы правите один и тот же код но при этом делаете разные задачи.

2024-02-05 20:06 UTC, IliaBYK commented
> @Olegas скорее всего так и есть, я писал об этом в описании к ПР, код с механиками игры еще на ревью, а моя задача сделать начало и конец игры, к сожалению не успели все обьединить, а дедлайн подкрался незаметно, но в дальнейшем, естественно, это будут составляющие одного целого

2024-02-05 20:20 UTC, Olegas commented
@IliaBYK как мне тогда сейчас проверять задачу если примерно 2/3 кода написана в другом PR? Если мы сейчас это заапрувим и сольем то подложим свинью коллеге которому придется чинить конфликты и переделывать свое решение. Правильным было бы поставить вашу ветку на ветку с механикой игры и от нее развивать код.

2024-02-06 15:22 UTC, Olegas commented
@IliaBYK Я заапрувил https://github.com/Glazoff/client-server-template-with-vite/pull/17 - может сделать твою ветку от этого PR и оставить только те изменения, про которые задача?

2024-02-06 16:04 UTC, IliaBYK commented
@Olegas да, конечно, буду сейчас думать как это скрестить все

2024-02-06 18:30 UTC, Olegas commented
@IliaBYK я имел ввиду https://github.com/Glazoff/client-server-template-with-vite/pull/15 а не 17 конечно же, ошибся

2024-02-07 13:56 UTC, IliaBYK commented
@Olegas сделал, но уже от ветки dev, оттуда изменения забирал

2024-02-08 12:24 UTC, Olegas requested changes
Есть замечания по организации переходов между состояниями. Нужно переделать. Написал где и что не так.

2024-02-08 12:24 UTC, Olegas commented on packages/client/src/widgets/MainGamePage/GameContent/index.tsx
> +  window.localStorage.setItem('score', score.toString());
Не надо так. Это будет каждый ренде в local storage писать одно и то же. У тебя есть колбэк на game over - в нем и надо писать

2024-02-08 12:24 UTC, Olegas commented on packages/client/src/widgets/MainGamePage/GameContent/index.tsx
> +    gameEngine?.gameOver && navigate(path.GameOver);
Вот это тоже опасная затея. Я не уверен что навигация не пересечется с выполнением той же записи в сторадж и например не произойдет раньше.
Есть колбэк на окончание игры, в нем надо сохранить очки и перейти на другую страницу - строго друг за другом. А читать постоянно флаг - не надо

2024-02-08 12:24 UTC, Olegas commented on packages/client/src/widgets/MainGamePage/GameContent/index.tsx
> +    /* gameEngine?.gameOver ? <GameOver /> :  */ <canvas
Не надо оставлять закомментированный код в проекте

2024-02-08 14:12 UTC, Olegas approved these changes
Работа принята, спасибо!

2024-02-08 14:47 UTC, merged