fullscreen mode
Glazoff/client-server-template-with-vite pull request #24
Opened 2024-02-24 14:41 UTC by kalikrit

### Какую задачу решаем
Добавить ещё одно WEB API (кроме Canvas, Fetch)

### Скриншоты/видяшка (если есть)
![fs_mode](https://github.com/Glazoff/client-server-template-with-vite/assets/7803486/c62c096a-c18b-4982-8cda-3dd4b1371a18)
![fs_mode1](https://github.com/Glazoff/client-server-template-with-vite/assets/7803486/0ff91cc7-fc78-4846-9527-321c33e58bfc)

### TBD (если есть)

2024-02-26 06:03 UTC, Glazoff approved these changes
Предложение, можно немного стилизовать кнопку под общий вид приложения.

2024-02-27 14:13 UTC, RinVeber approved these changes

2024-02-28 16:51 UTC, IvanPeleshok commented on packages/client/src/components/Layout/Layout.tsx
> +          onClick={() => {
Предлагаю выносить инлайнколбеки, т.к их невозможно оптимизировать и достаточно сложно читать (если файл объёмный)

2024-02-28 16:54 UTC, IvanPeleshok commented on packages/client/src/components/Layout/Layout.tsx
> +              document.querySelector('#btnFS') as HTMLElement
Каждый раз, когда будет вызван клик, мы будем искать дом элемент, что является дорогой операцией - этого в контексте реакта необходимо избегать

Предлагаю воспользоваться хуком useRef: https://legacy.reactjs.org/docs/hooks-reference.html#useref, для получения ссылки на элемент

2024-02-28 16:55 UTC, IvanPeleshok commented on packages/client/src/components/Layout/Layout.tsx
> +          onClick={() => {
const Component: FC = () => {
  handleClick = () => { ... }
  
  return <div  onClick={handleClick} />
}

2024-02-28 16:56 UTC, IvanPeleshok commented on packages/client/src/components/Layout/Layout.tsx
> +          id="btnFS"
Предлагаю не сокращать названия, чтобы код был более человекочитаемым (buttonFullscreen)

2024-02-28 16:56 UTC, IvanPeleshok commented on packages/client/src/shared/helperFunction/toggleFullScreenFunction.ts
> +  elem = elem || document.documentElement;
element

2024-02-28 17:06 UTC, IvanPeleshok commented on packages/client/src/shared/helperFunction/toggleFullScreenFunction.ts
> +    button.textContent = 'выход из полноэкранного режима';
В контексте реакта это неоптимальный подход отрисовки динамического контента

Предлагаю воспользоваться useState в компоненте, который будет отвечать за текущий режим отображения (полноэкранный / неполноэкранный), где toggleFullscreen будет возвращать некоторое значение, которое будет менять значение для переменной из useState: https://legacy.reactjs.org/docs/hooks-reference.html#usestate

```
const Component: FC = () => {
   const [isFullscreen, setIsFullscreen] = useState(false)

   const handleClick = () => {
     const isFullscreen = toggleFullscreen()
     
     setIsFullscreen(isFullscreen)
   }
   
   return (
     <button onClick={handleClick}>
       {isFullscreen ? 'Cancel' : 'Apply'}
     </button>
 )
  ```
  
В идеале, было бы здорово реализовать свой кастомный хук, который будет содержать в себе всю необходимую логику с кликом и текущего состояния режима показа

2024-02-28 17:09 UTC, IvanPeleshok commented on packages/client/src/shared/helperFunction/toggleFullScreenFunction.ts
> +    if (elem.requestFullscreen) {
Супер, что позаботились об обратной совместимости для браузеров

2024-02-28 17:10 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Работа требует доработок, предлагаю поправить

Хорошего дня :)

2024-02-29 18:37 UTC, kalikrit commented on packages/client/src/components/Layout/Layout.tsx
> +          onClick={() => {
я правильно понял - вынести все в отдельный компонент?

2024-02-29 18:49 UTC, kalikrit commented on packages/client/src/components/Layout/Layout.tsx
> +          id="btnFS"
поправил

2024-03-01 06:09 UTC, IvanPeleshok commented on packages/client/src/components/FullScreen.tsx
> +  const handleClick = (event: MouseEvent) => {
Тип будет следующим
```
event: React.MouseEvent<HTMLButtonElement>

2024-03-01 06:10 UTC, IvanPeleshok commented on packages/client/src/components/FullScreen.tsx
> +      self.textContent = 'выход из полноэкранного режима';
Как уже ранее писал, то работа с динамическим контентом в реакте реализуется относительно условностей и "реактивных" переменных, которые могут триггерить перерисовку: https://github.com/Glazoff/client-server-template-with-vite/pull/24/files#r1506300716

Поправьте, в соответствии с замечанием, пожалуйста

2024-03-01 06:11 UTC, IvanPeleshok commented on packages/client/src/shared/helperFunction/toggleFullScreenFunction.ts
> +export default function toggleFullscreen(elem: HTMLElement, button: HTMLElement) {
Если более не используется, то предлагаю удалить неиспользуемый функционал

2024-03-01 06:12 UTC, IvanPeleshok commented on packages/client/src/components/FullScreen.tsx
> +import { MouseEventHandler } from 'react';
Импортирован, но не используется

2024-03-01 06:13 UTC, IvanPeleshok requested changes
Добрый день!

Не все замечания поправлены, предлагаю доработать

Хорошего дня :)

2024-03-02 14:00 UTC, kalikrit commented on packages/client/src/components/Layout/Layout.tsx
> +          onClick={() => {
вынес в отдельный компонент

2024-03-02 15:30 UTC, kalikrit commented on packages/client/src/components/Layout/Layout.tsx
> +              document.querySelector('#btnFS') as HTMLElement
вынес в отдельный компонент, 
теперь кнопка в компоненте и ничего искать не надо

2024-03-02 16:33 UTC, kalikrit commented on packages/client/src/shared/helperFunction/toggleFullScreenFunction.ts
> +    button.textContent = 'выход из полноэкранного режима';
сделал
эта реализация мне нравится гораздо больше предыдущей!
супер! спасибо

2024-03-02 16:33 UTC, kalikrit commented on packages/client/src/components/FullScreen.tsx
> +  const handleClick = (event: MouseEvent) => {
отказался от этого

2024-03-02 16:34 UTC, kalikrit commented on packages/client/src/components/FullScreen.tsx
> +      self.textContent = 'выход из полноэкранного режима';
сделал по-другому

2024-03-02 16:34 UTC, kalikrit commented on packages/client/src/components/FullScreen.tsx
> +import { MouseEventHandler } from 'react';
отказался от этого

2024-03-03 08:47 UTC, IvanPeleshok requested changes
Добрый день
Отлично постарались!
MR почти готов к апруву, есть небольшие моменты, которые стоит поправить

2024-03-03 08:47 UTC, IvanPeleshok commented on yarn.lock
Для чего удалили yarn.lock?
Предлагаю добавить его в MR

2024-03-03 08:47 UTC, IvanPeleshok commented on packages/client/src/components/FullScreen.tsx
> +  const toggleFullScreen = () => {
Данный метод можно вынести из компонента в отдельный модуль, как у вас было ранее

2024-03-03 08:47 UTC, IvanPeleshok commented on packages/client/src/components/FullScreen.tsx
> +    <button id="buttonFullScreen" onClick={handleClick}>
Полагаю, что id уже не нужен

2024-03-03 08:47 UTC, IvanPeleshok commented on yarn-error.log
Для чего удалили yarn-error.log?
Предлагаю его вернуть в MR

2024-03-03 18:57 UTC, kalikrit commented on packages/client/src/components/FullScreen.tsx
> +    <button id="buttonFullScreen" onClick={handleClick}>
удалил

2024-03-03 18:58 UTC, kalikrit commented on packages/client/src/components/FullScreen.tsx
> +  const toggleFullScreen = () => {
вынес в shared/helperFunction/toggleFullScreen

2024-03-03 19:03 UTC, kalikrit commented on yarn.lock
добавил свой yarn.lock
пока висел МР, другие ребята из команды вмержили в dev свои задачи
и теперь эта ветка конфликтует файлом yarn.lock с dev
мы разрешим конфликты командой
мерж дева в эту ветку не помог

2024-03-03 19:05 UTC, kalikrit commented on yarn-error.log
попробовал использовать dev-овский yarn.lock
но с ним ничего не запустилось, появился yarn-error.log
откатил назад и удалил этот файл у себя

2024-03-04 15:10 UTC, IvanPeleshok commented on yarn.lock
Окей, надеюсь, что на этапе мержа разберётесь с данным кейсов
По фиче всё гуд :)

2024-03-04 15:10 UTC, IvanPeleshok approved these changes
Прекрасная работа!
Поздравляю, апрув!

Хорошего дня :)

2024-03-04 17:50 UTC, merged